services:
  web:
    build: ./frontend
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
          
volumes:
  jobs:
    