services:
  web:
    depends_on:
      - api
    build: ./frontend
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
  api:
    build:
      context: ./backend/JobListingsApi
      target: final
    ports:
      - 5000:80
volumes:
  jobs:
    