networks:
    dev:
        driver: bridge

services:
  web:
    depends_on:
      - api
    build: ./frontend
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
  api:
    depends_on:
      - db
    build:
      context: ./backend/JobListingsApi
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      - ConnectionStrings_DefaultConnection=User ID=postgres;Password=postgres;Server=db;Port=5432;Database=SampleDbJobListings;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    links:
      - "db:db"
    networks:
      - dev

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SampleDbJobListings
    ports:
      - 5433:5432
    restart: always
    volumes:
      - jobs:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  jobs:
    